localStorage.clear();
export const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Complete Project Report",
        taskDescription: "Prepare and submit the final project report.",
        taskCategory: "Work",
        date: "2025-04-05",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        taskTitle: "Team Meeting",
        taskDescription: "Attend the weekly team meeting on Zoom.",
        taskCategory: "Meetings",
        date: "2025-04-06",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "Code Review",
        taskDescription: "Review the latest pull requests from the team.",
        taskCategory: "Development",
        date: "2025-04-07",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
    ],
    taskCount: {
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
      activeTask: 2,
    },
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Fix UI Bugs",
        taskDescription: "Resolve reported UI issues in the dashboard.",
        taskCategory: "Development",
        date: "2025-04-04",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        taskTitle: "Client Presentation",
        taskDescription: "Prepare slides and present the new product features.",
        taskCategory: "Work",
        date: "2025-04-05",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "Database Optimization",
        taskDescription: "Analyze and improve database query performance.",
        taskCategory: "Development",
        date: "2025-04-08",
        active: false,
        completed: false,
        newTask: false,
        failed: true,
      },
    ],
    taskCount: {
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
      activeTask: 1,
    },
  },
  {
    id: 3,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Write Documentation",
        taskDescription: "Update API documentation for the new release.",
        taskCategory: "Work",
        date: "2025-04-06",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        taskTitle: "Security Audit",
        taskDescription: "Perform a security audit of the backend services.",
        taskCategory: "Security",
        date: "2025-04-07",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "Testing New Features",
        taskDescription: "Test and report bugs for the new module.",
        taskCategory: "Testing",
        date: "2025-04-09",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
    ],
    taskCount: {
      newTask: 2,
      completedTask: 1,
      failedTask: 0,
      activeTask: 2,
    },
  },
  {
    id: 4,
    name: "David Wilson",
    email: "david.wilson@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Write Blog Post",
        taskDescription: "Draft a blog post about recent tech trends.",
        taskCategory: "Writing",
        date: "2025-04-10",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "System Migration",
        taskDescription: "Migrate the old system to the new infrastructure.",
        taskCategory: "Infrastructure",
        date: "2025-04-12",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "Update Software Dependencies",
        taskDescription: "Upgrade outdated dependencies in the project.",
        taskCategory: "Development",
        date: "2025-04-14",
        active: false,
        completed: false,
        newTask: true,
        failed: false,
      },
    ],
    taskCount: {
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
      activeTask: 1,
    },
  },
  {
    id: 5,
    name: "Emma Brown",
    email: "emma.brown@example.com",
    password: "123",
    tasks: [
      {
        taskTitle: "Social Media Campaign",
        taskDescription: "Plan and execute a social media marketing campaign.",
        taskCategory: "Marketing",
        date: "2025-04-11",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        taskTitle: "Customer Feedback Analysis",
        taskDescription: "Analyze customer feedback from surveys.",
        taskCategory: "Analytics",
        date: "2025-04-13",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        taskTitle: "Create UI Wireframes",
        taskDescription: "Design UI wireframes for the new mobile app.",
        taskCategory: "Design",
        date: "2025-04-15",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
    ],
    taskCount: {
      newTask: 1,
      completedTask: 1,
      failedTask: 0,
      activeTask: 2,
    },
  },
];
export const admin = {
  id: 100,
  name: "Admin User",
  email: "admin@example.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employeesData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));

  return { employeesData, adminData };
};
