const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    password: "123",
    tasks: [
      {
        title: "Complete Project Report",
        description: "Prepare and submit the final project report.",
        category: "Work",
        date: "2025-04-05",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Attend the weekly team meeting on Zoom.",
        category: "Meetings",
        date: "2025-04-06",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        title: "Code Review",
        description: "Review the latest pull requests from the team.",
        category: "Development",
        date: "2025-04-07",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix UI Bugs",
        description: "Resolve reported UI issues in the dashboard.",
        category: "Development",
        date: "2025-04-04",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        title: "Client Presentation",
        description: "Prepare slides and present the new product features.",
        category: "Work",
        date: "2025-04-05",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        title: "Database Optimization",
        description: "Analyze and improve database query performance.",
        category: "Development",
        date: "2025-04-08",
        active: false,
        completed: false,
        newTask: false,
        failed: true,
      },
    ],
  },
  {
    id: 3,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    password: "123",
    tasks: [
      {
        title: "Write Documentation",
        description: "Update API documentation for the new release.",
        category: "Work",
        date: "2025-04-06",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        title: "Security Audit",
        description: "Perform a security audit of the backend services.",
        category: "Security",
        date: "2025-04-07",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        title: "Testing New Features",
        description: "Test and report bugs for the new module.",
        category: "Testing",
        date: "2025-04-09",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    name: "David Wilson",
    email: "david.wilson@example.com",
    password: "123",
    tasks: [
      {
        title: "Write Blog Post",
        description: "Draft a blog post about recent tech trends.",
        category: "Writing",
        date: "2025-04-10",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        title: "System Migration",
        description: "Migrate the old system to the new infrastructure.",
        category: "Infrastructure",
        date: "2025-04-12",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
      {
        title: "Update Software Dependencies",
        description: "Upgrade outdated dependencies in the project.",
        category: "Development",
        date: "2025-04-14",
        active: false,
        completed: false,
        newTask: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    name: "Emma Brown",
    email: "emma.brown@example.com",
    password: "123",
    tasks: [
      {
        title: "Social Media Campaign",
        description: "Plan and execute a social media marketing campaign.",
        category: "Marketing",
        date: "2025-04-11",
        active: true,
        completed: false,
        newTask: true,
        failed: false,
      },
      {
        title: "Customer Feedback Analysis",
        description: "Analyze customer feedback from surveys.",
        category: "Analytics",
        date: "2025-04-13",
        active: false,
        completed: true,
        newTask: false,
        failed: false,
      },
      {
        title: "Create UI Wireframes",
        description: "Design UI wireframes for the new mobile app.",
        category: "Design",
        date: "2025-04-15",
        active: true,
        completed: false,
        newTask: false,
        failed: false,
      },
    ],
  },
];

const admin = {
  id: 100,
  name: "Admin User",
  email: "admin@example.com",
  password: "123",
};
